### PR TITLE
Fixed IaitoCore::getBreakpoints

### LINKED ISSUE #60: Segmentation fault when opening windows binaries
## Environment Details

```sh
QCommandLineParser: already having an option named "w"
iaito 5.2.2
Fri Nov  5 20:12:43 CET 2021
radare2 5.4.3 26997 @ linux-x86-64 git.5.4.2
commit: f0ffdde6b6f54f440f5a6920e88de46a60ca8f4f build: 2021-11-04__14:12:46
Linux x86_64
```
iaito is installed from the master branch and is up to date.

## Description

When trying to open a project iaito crashes with a Segmentation fault after the analysis is done.

Output (disabled analysis):
```
QCommandLineParser: already having an option named "w"
WARNING: r_event_hook: assertion 'ev' failed (line 59)
Plugins are loaded from "/home/****/.local/share/radareorg/iaito/plugins"
Loaded 0 plugin(s).
Plugins are loaded from "/usr/local/share/radareorg/iaito/plugins"
Plugins are loaded from "/usr/share/radareorg/iaito/plugins"
Segmentation fault (core dumped)
```
## How to reproduce
Open iaito, open an executable, wait for the analysis to finish and it will crash.
This seems to only happens with Windows binaries, I didn't encounter it with ELF executables.

### PR DESCRIPTION
**Pull request by Kakiking**
**Detailed description**

This function was responsible for a segfault when loading any Windows binary
It now uses the API as the TODO above said.

**Closing issues**
Closes #60

### CODE REVIEW

File: src/core/Iaito.cpp [hunk 1]
```diff
@@ -2237,11 +2237,10 @@ QList<BreakpointDescription> IaitoCore::getBreakpoints()
...
     CORE_LOCK();
     QList<BreakpointDescription> ret;
-    //TODO: use higher level API, don't touch r2 bps_idx directly
-    for (int i = 0; i < core->dbg->bp->bps_idx_count; i++) {
-        if (auto bpi = core->dbg->bp->bps_idx[i]) {
-            ret.push_back(breakpointDescriptionFromR2(i, bpi));
-        }
+    for (int i = 0;; i++) {
+        RBreakpointItem *bpi = r_bp_get_index(core->dbg->bp, i);
+        if (!bpi) break;
```
Comment (trufae) [inline src/core/Iaito.cpp:2242]:
```suggestion
        if (!bpi) continue;
```

**Review by trufae — APPROVED** [review]
